version: "3.7"
services:
  db:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=loteria
    volumes:
      - ./resultados.csv:/opt/app/resultados.csv
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bolao_net

networks:
  bolao_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "111.111.10.0/24"
